apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: users-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containerMode: kubernetes
      workVolumeClaimTemplate:
        storageClassName: "csi-cinder-classic"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      serviceAccountName: github-runner-sa  
      repository: rooty123/users
      labels:
        - linux
        - abc
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: telegram-api-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containerMode: kubernetes
      workVolumeClaimTemplate:
        storageClassName: "csi-cinder-classic"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      serviceAccountName: github-runner-sa  
      repository: rooty123/telegram-api
      labels:
        - linux
        - abc